### PR TITLE
fix reliaca Status bug

### PR DESCRIPTION
**Pull request by chenxinya**
fix ckman table page table replica status is wrong 
because the clickhouse is upgrade
// Remove leader election, step 2: allow multiple leaders https://github.com/ClickHouse/ClickHouse/pull/11639

### CODE REVIEW

**Comment by YenchangChan** [comment]
Which version have this feature？ Maybe it would be better to use the following code：
```go
if common.CompareClickHouseVersion(currentVersion,  featureVersion) >= 0 {
    //new logic
} else {
   //old logic
}
```

**Comment by chenxinya** [comment]
> Which version have this feature？ Maybe it would be better to use the following code：
> 
> ```go
> if common.CompareClickHouseVersion(currentVersion,  featureVersion) >= 0 {
>     //new logic
> } else {
>    //old logic
> }
> ```

How can i get currentVersion？The version is 20.5 which having this feature.

**Comment by YenchangChan** [comment]
> > Which version have this feature？ Maybe it would be better to use the following code：
> > ```go
> > if common.CompareClickHouseVersion(currentVersion,  featureVersion) >= 0 {
> >     //new logic
> > } else {
> >    //old logic
> > }
> > ```
> 
> How can i get currentVersion？The version is 20.5 which having this feature.

ckman will store clickhouse version in cluster config， you can get it from `CKManClickHouseConfig.Version`

**Comment by chenxinya** [comment]
already change Judgment logic

**Pull request merged**
