### PR TITLE
fix: restart cluster when change profiles and quotas

### PR DESCRIPTION
**Pull request by YenchangChan**

### CODE REVIEW

**Comment by FWLamb** [comment]
Does the cluster restart after changing the profile or quota configuration?

**Comment by yuzhichang** [comment]
@FWLamb No.

**Comment by FWLamb** [comment]
> @FWLamb No.

那请问什么情况下会重启集群呢？

**Comment by YenchangChan** [comment]
修改profiles和quotas会重启的，如果只修改用户名、密码那些不会重启

**Pull request merged**
